image: buildpack-deps:latest

stages:
  - build

before_script:
  - apt-get update -y
  - apt-get install -y gcc make libsdl2-dev libsdl2-image-dev libsdl2-gfx-dev

compile:
  stage: build
  script:
    - cd src
    - make
  artifacts:
    paths:
      - src/circles
    expire_in: 1 week
  only:
    - branches
